### PR TITLE
[Feature #161278916] add comments to articles

### PR DESCRIPTION
**Pull request by susanwere**
#### What does this PR do?
Implements feature to add comments to an article
#### Description of Task to be completed?

1.  Post comment on an article
2. Thread comments
3. Edit a comment
4. Get a specific comment
5. Delete a comment

#### How should this be manually tested?
1. git clone https://github.com/andela/ah-sealteam
2. cd ah-sealteam
3. python manage.py makemigrations articles
4. python manage.py migrate
5. python manage.py runserver

#### To add a comment to an article and get an article's comments

`<slug:slug>/comments/`

`{
	"body":"a comment"
}`

#### To edit a comment, delete a comment, add a thread to a comment and get a comment

`<slug:slug>/comments/<int:id>/`

`{
	"body":"a comment"
}`

#### What are the relevant pivotal tracker stories?

[#161278916](https://www.pivotaltracker.com/story/show/161278916)

#### Post Comment
post

#### Get comments of an article
getcomments

#### Edit a comment
edit a comment

#### Delete a comment
delete

#### Add a thread to a comment
screen shot 2018-11-07 at 11 22 53

#### Get a specific comment with its thread
getspecificcomment

### CODE REVIEW

**Review by rickynyairo — APPROVED** [review]
For REST APIs, the name of a resource should be in plural. In your case, the resource is 'comments'. Therefore, the url should have:

/api/articles/<slug:slug>/comments/
/api/articles/<slug:slug>/comments/<int:id>/

You may consider changing that. 
However, great work: worthy an approval. This should be as easy as adding an s in the urlpatterns.

**Review by asheux — APPROVED** [review]
Awesome work. But you could ensure the coverage doesn't drop.

Noted. Working on it.

**Review by Adoniswalker — CHANGES_REQUESTED** [review]
Good work with nesting payload, permissions, and more test
But am concerned with 1 thing

1.  I managed to post 20 comments and sub comments with one body. Consider using a foreign key

This has been implemented.

**Comment by rickynyairo** [comment]
@Adoniswalker In the case of posting a comment with the same body, I would think it is possible that more than one user can want to say, for example, "Thank you for that piece". In such a case, limiting the number of occurrences of a single body of a comment would be unnecessarily restrictive. What do you think @Bluey95 ?

**Review by Adoniswalker — APPROVED** [review]

**Review by gtsofa — APPROVED** [review]

**Review by botnetdobbs — CHANGES_REQUESTED** [review]
I've seen that a user can post the same comment over and over again. Kindly try to ensure that the same user cannot post the same comment more than once.
EDIT: Approved as we look for a workaround on this...,

**Review by botnetdobbs — APPROVED** [review]

**Pull request merged**
