### PR TITLE
[Feature #161278913] Add create article functionality

### PR DESCRIPTION
**Pull request by asheux**
#### What does this PR do?
- Creates the functionality for users to create, get(one), get(all) articles in the application

#### Description of Task to be completed?

- When a user is authenticated or is logged into the application, they can be able to post an article in the app for other users to read and react on. The users can also get a single and all articles whether logged in or not.

#### How should this be manually tested?
```
$ git clone https://github.com/andela/ah-sealteam
$ cd ah-sealteam
$ pip install -r requirements.txt
$ python manage.py makemigrations
$ python manage.py migrate
$ python manage.py runserver
```
- Go to [127.0.0.1:8000/api](http://127.0.0.1:8000/api) to test in on swagger
#### Any background context you want to provide?
- Django [Documentation](https://docs.djangoproject.com/en/2.1/ref/contrib/contenttypes/)
- Django restframework Api [docs](https://www.django-rest-framework.org/api-guide/relations/#generic-relationships)
#### What are the relevant pivotal tracker stories?
- [161278913](https://www.pivotaltracker.com/n/projects/2205273/stories/161278913)

#### Screenshots (if appropriate)
create

#### Get a single article
one

#### Get all articles

all

#### Questions:

### CODE REVIEW

**Comment by botnetdobbs** [comment]
Rectify the fetching of questions. The user should not be authenticated to view all articles.
Also, I get this error when I try to post an article of more than 500 characters.
screen shot 2018-11-04 at 20 50 51

**Comment by asheux** [comment]
Thanks. 
I already worked on that. Try to test it again.

**Review by susanwere — CHANGES_REQUESTED** [review]
I am getting a runtime error during post. 

`You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set`

**Review by Adoniswalker — APPROVED** [review]

**Review by susanwere — APPROVED** [review]

**Review by botnetdobbs — APPROVED** [review]

**Comment by Adoniswalker** [comment]
Mboya will rebase develop

**Pull request merged**
