### PR TITLE
[feature #161278908] Email verification link on user sign up

### PR DESCRIPTION
**Pull request by gtsofa**
### What does this PR do
This test if a user can receive a verification link on sign up and 
User clicks on that link to verify their account 

### Description of Task to be completed?

1. When a user signs up on our platform, he or she should receive an email verification link.
2. When the user clicks on the link provided, he or she should be redirected to verify account page
3. When the user doesn't click the link within the time set, the link expires in which they will need to request for a new link.

### How should this be manually tested?*
On your git repo run
$ `git fetch origin pull/22/head:ft-user-email-verification-161278908`
checkout to the feature branch
$ `git checkout  ft-user-email-verification-161278908`
> register a new user on the postman
> Go to your email and verify your account by clicking the link
> You should see a successfully verified message
> After 30 seconds the ur
### Screenshot(s) available
Click link to verify account
screen shot 2018-11-08 at 10 18 49
Verify account page
screen shot 2018-11-08 at 10 17 21

### What are the relevant pivotal tracker stories?
[161278908](https://www.pivotaltracker.com/story/show/161278908)

### CODE REVIEW

**Review by Adoniswalker — COMMENTED** [review]
Work on feedback requested

**Review by Adoniswalker — CHANGES_REQUESTED** [review]
Work on feedback requested

**Review by susanwere — CHANGES_REQUESTED** [review]
Confirm email button isn't working

**Comment by gtsofa** [comment]
@Bluey95 , I think the problem is on the environment variables. Sorry, I didn't include that in my instructions. Add this `export DOMAIN="http://127.0.0.1:8000"` to your .env file and source it let me know if it works.

**Review by rickynyairo — COMMENTED** [review]
I'm getting a 404 not found when I click the link. 
I believe it is a problem with how the url is structured. Please review

**Review by susanwere — APPROVED** [review]

**Review by botnetdobbs — APPROVED** [review]

**Review by Adoniswalker — APPROVED** [review]

**Review by rickynyairo — APPROVED** [review]

**Review by asheux — APPROVED** [review]

**Pull request merged**
