### PR TITLE
#161278900 Integrate TravisCI with readme badge

### PR DESCRIPTION
**Pull request by susanwere**
[Build Status](https://travis-ci.org/andela/ah-sealteam)

**What does this PR do?**

It integrates TravisCI with readme badge to the application

**Description of Task to be completed?**

1. Create .travis.yml file and add the neccessary dependencies

              - define language the application is developed in
              - define multiple versions of python for testins
              - define services required for application
              - specify django application version
              - specify database to use
              - add command to install requirements
              - add commands to run before running tests in before_script
              - add commands to run tests

**How should this be manually tested?**

Click or view the added badge in order to view the build status of the application

**What are the relevant pivotal tracker stories?**

[#161278900](https://www.pivotaltracker.com/story/show/161278900)

### CODE REVIEW

**Comment by rickynyairo** [comment]
Nice... we'll include more environment vars for the DB once the database setup PR has been merged.

**Comment by gtsofa** [comment]
PR is well implemented as specified on the task assigned.

**Comment by botnetdobbs** [comment]
Good. Tasks well specified.

**Review by rickynyairo — APPROVED** [review]
I think it will be better if we had only one python version running for Travis. Since we're all using 3.7, it would be best if you removed the other 2 versions.

**Review by botnetdobbs — APPROVED** [review]

**Pull request merged**
