### PR TITLE
#161278901 Set up Postgresql as DB engine

### PR DESCRIPTION
**Pull request by botnetdobbs**
### What does this PR do?
- Configure the app to work with Postgresql
### Description of Task to be completed?
- Add environment variables and fetching them from the settings.py
- Add psycopg2 and accompanying dependencies to requirements.txt
### How should this be manually tested
- clone the Repo 'git clone https://github.com/andela/ah-sealteam.git'
- Install Virtualenv `pip install virtualenv`
- Create the virtual environment `virtualenv venv`
- Activate the virtualenv `source venv/bin/activate`
- navigate to project folder `cd ah-sealteam`
- Install the dependencies `pip install -r requirements.txt`
- Run the migrations `python manage.py makemigrations && python manage.py migrate`
#### What are the relevant pivotal tracker stories?
- [Finishes #161278901]

### CODE REVIEW

**Comment by gtsofa** [comment]
@botnetdobbs , on the repo that I just clone from your PR is ah-sealteam , why do I have to navigate to project folder `StackOverflowLiteApi` on your instruction number 3?

**Comment by botnetdobbs** [comment]
> @botnetdobbs , on the repo that I just clone from your PR is ah-sealteam , why do I have to navigate to project folder `StackOverflowLiteApi` on your instruction number 3?

My mind is still not far from the Boot camp project...,

**Comment by asheux** [comment]
Use the engineers playbook to write your commit messages

**Comment by rickynyairo** [comment]
Your PR shows that you branched from master. You should branch from develop.

**Comment by botnetdobbs** [comment]
Lemme create a new PR

**Pull request closed without merging**
