### PR TITLE
chore(reset): implement login after password reset

### PR DESCRIPTION
**Pull request by susanwere**
#### What does this PR do?

Refactors Feature To Reset Password

#### Description of Task to be completed?

1.  Allow users to log in after reset password

#### How should this be manually tested?

1. git clone https://github.com/andela/ah-sealteam
2. cd ah-sealteam
3. python manage.py makemigrations articles
4. python manage.py migrate
5. python manage.py runserver

#### To Request For A Password

`users/forgotpassword/`

`{
	"email":"your email"
}`

#### To Reset your password

`users/resetpassword/<token>/`

`{
	"new_password":"newpassword",
	"confirm_password":"newpassword",
	"email":"your_email"
}`

#### What are the relevant pivotal tracker stories?

[#161776514](https://www.pivotaltracker.com/story/show/161776514)

#### Forgot Password
forgotpass

#### Reset Password
resetpass

### CODE REVIEW

**Review by asheux — APPROVED** [review]
The work is great

**Review by botnetdobbs — APPROVED** [review]

**Comment by botnetdobbs** [comment]
Good job...,

**Review by gtsofa — APPROVED** [review]

**Review by Adoniswalker — APPROVED** [review]
V. good

**Comment by gtsofa** [comment]
@Bluey95, good implementation of reset password. Good job on the reset password page.

**Comment by proxiex** [comment]
I think you are supposed to ignore `.DS_Store` file

**Pull request merged**
