### PR TITLE
[Feature #161278910] Implement Feature To Reset Password

### PR DESCRIPTION
**Pull request by susanwere**
#### What does this PR do?
- Implements password reset via email

#### Description of Task to be completed?
- To implement sendGrid API for email verification
- To implement an api endpoint for new password request
- To implement an api endpoint for password reset

#### How should this be manually tested?*

1. Update .env file with the following details

         - export EMAIL_HOST_USER='your_smtp_username'
         - export EMAIL_HOST_PASSWORD='your_smtp_password'

```
$ git clone https://github.com/andela/ah-sealteam
$ cd ah-sealteam
$ git checkout `ft-reset-passsword-161278910`
$ python manage.py makemigrations
$ python manage.py migrate
$ python manage.py runserver
$ use http://127.0.0.1:8000/api/users/ to register a new user

```
```
{
     "user":
             {
                   "email":"your_working_email",
                   "username":"your_username",
                   "password":"your_password"
             }
}
```
```                 
$ use http://127.0.0.1:8000/api/users/forgotpassword to request for a new password 
```
```
       {
                   "email":"your_registered_email"
        }

```
```                 
$ use http://127.0.0.1:8000/api/users/resetpassword to reset your password 
```
```
       {
	    "email":"your_registered_email",
	    "password":"newpassword",
	    "token":"generatedtoken"
      }

```
OR 

Open this [http://127.0.0.1:8000/api/](http://127.0.0.1:8000/api/) link in your browser to use the documentation

#### What are the relevant pivotal tracker stories?
[#161278910](https://www.pivotaltracker.com/story/show/161278910)

### CODE REVIEW

**Review by botnetdobbs — APPROVED** [review]

**Comment by Adoniswalker** [comment]
Is it a good idea to return the token when the user request a password resetting? It may be a security issue
Am getting this when i dont provide a payload _KeyError at /api/users/resetpassword/
'user'_ on resetpassword
Good work there

**Comment by susanwere** [comment]
> Thank you. Let me fix that

**Review by Adoniswalker — CHANGES_REQUESTED** [review]
Kindly Test both worst and best case

**Comment by gtsofa** [comment]
a user gets a token and a reset password link via mail.

**Review by gtsofa — APPROVED** [review]

**Comment by asheux** [comment]
The reset password is working perfectly, although there is a problem with the response message when I tried to log in with my old password. The message is too detailed and long.

**Review by asheux — CHANGES_REQUESTED** [review]
The reset password is working perfectly, although there is a problem with the response message when I tried to log in with my old password. The message is too detailed and long.

**Review by Adoniswalker — APPROVED** [review]
Good work.
If you can test reset passsword. 
Use pylint next time.

**Review by asheux — APPROVED** [review]

**Pull request merged**
