### PR TITLE
[Feature #161278927] Add article bookmark functionality

### PR DESCRIPTION
**Pull request by asheux**
#### What does this PR do?
- Implements the functionality for users to be able to bookmark articles

#### Description of Task to be completed?
- When users feel like they have no time to read the article but can find sometime later, they can bookmark the article for them to read later

#### How should this be manually tested?
```
$ git fetch origin pull/32/head:ft-articles-bookmarking-161278927
$ git checkout ft-articles-bookmarking-161278927
$ python manage.py makemigrations
$ python manage.py migrate
$ python manage.py runserver
```
Testing on postman
go to [http://127.0.0.1:8000/api/<article_slug>/bookmark/](http://127.0.0.1:8000)
GET http://127.0.0.1:8000/api/articles/bookmarks/ all bookmarks
POST new bookmark http://127.0.0.1:8000/api/articles/{slug}bookmark/
DELETE bookmark http://127.0.0.1:8000/api/articles/{slug}/bookmark/
#### What are the relevant pivotal tracker stories?
- [161278927](https://www.pivotaltracker.com/n/projects/2205273/stories/161278927)

### CODE REVIEW

**Comment by rickynyairo** [comment]
Hi Brian, great work. 
I would suggest restructuring your feature to be a separate Django application. This makes your code re-usable and easy to integrate into other applications.

**Review by Adoniswalker — DISMISSED** [review]
This PR will lower out test coverage. Kindly explain why or try to test all Input-output scenario.

**Review by botnetdobbs — APPROVED** [review]

**Comment by botnetdobbs** [comment]
@Adoniswalker I agree...,

**Comment by botnetdobbs** [comment]
@asheuh Kindly check on the Travis Build...,

**Review by susanwere — COMMENTED** [review]
Great Work.

Kindly add the specific endpoints to be tested on the PR in order to allow for review

**Comment by asheux** [comment]
> Travis B

**Comment by botnetdobbs** [comment]
@asheuh Good job on the coverage...,

**Review by Adoniswalker — APPROVED** [review]

**Review by gtsofa — APPROVED** [review]

**Review by susanwere — APPROVED** [review]

**Review by rickynyairo — APPROVED** [review]

**Review by gtsofa — APPROVED** [review]

**Pull request merged**
