### PR TITLE
[Finished #161278924] Enable searching articles

### PR DESCRIPTION
**Pull request by gtsofa**
### What does this PR do
A user is able to search for articles by author, article title and tag/keyword or search by filtering.
### Description of Task to be completed?
This is how the search is done:-
1. If only author is supplied on the search parameter - the filter will only filter by author
2. If only tag is supplied as the search parameter - the filter will only filter by tag
3. If only keywords are supplied as the search parameter, the filter will only filter by keywords.
4. If any of the above is supplied, the filter filters by the supplied filters

### How should this be manually tested?*
On your git repo run
$ `git fetch origin pull/31/head:ft-article-searching-161278924`
checkout to the feature branch
$ `git checkout  ft-article-searching-161278924`
> Login  on  postman
> Search articles by author, tag, title and keyword.
### Screenshot(s) available
Search by keywords
screen shot 2018-11-09 at 10 08 26

Search by title, tag and author
screen shot 2018-11-09 at 10 09 07

### What are the relevant pivotal tracker stories?
[161278924](https://www.pivotaltracker.com/story/show/161278924)

### CODE REVIEW

**Review by botnetdobbs — APPROVED** [review]
After reviewing the code the functionality and I can say you did a good job.

**Review by asheux — APPROVED** [review]
Good teamwork. The feature works fine

**Review by rickynyairo — APPROVED** [review]

**Review by susanwere — APPROVED** [review]

**Comment by rickynyairo** [comment]
The PR can use some improvement

**Comment by Adoniswalker** [comment]
> The PR can use some improvement

I have been able to improve the searching by making the searching username and tags case insensitive. Kindly update me if there is anything you need to be improved

**Pull request merged**
