### PR TITLE
[Feature #161278930] Track Edit History

### PR DESCRIPTION
**Pull request by susanwere**
#### What does this PR do?
- Implements the functionality to track the edit history of an article's comments

#### Description of Task to be completed?
- Implement a feature that will allow a user to view previous comments

#### How should this be manually tested?
```
$ git fetch origin pull/37/head:ft-track-comment-edit-history-161278930
$ git checkout ft-track-comment-edit-history-161278930
$ python manage.py makemigrations
$ python manage.py migrate
$ python manage.py runserver
```
### To View Previous Comments After Editing A comment
`
GET

`articles/<slug:slug>/comments/<int:id>/previous`
`

### To View All Previous Comments of an article
`
GET

`articles/<slug:slug>/comments/<int:id>/allprevious`
`

### What are the relevant pivotal tracker stories?
- [#161278930](https://www.pivotaltracker.com/story/show/161278930)

### CODE REVIEW

**Review by botnetdobbs — APPROVED** [review]
Reviewed and the endpoints are working as expected. Good job...,
screen shot 2018-11-14 at 12 05 22

**Review by gtsofa — APPROVED** [review]

**Review by asheux — APPROVED** [review]
Great work


Thank you

**Review by rickynyairo — APPROVED** [review]
- Good work
- We should consider adding the same functionality for an article. 


Very True Ricky

**Review by Adoniswalker — APPROVED** [review]
Good work, you can also paginate the comments and history


Thank you. Updated now. I have implemented pagination.

**Pull request merged**
