### PR TITLE
[Feature #161278918] Users should be able to follow each other

### PR DESCRIPTION
**Pull request by botnetdobbs**
### What does this PR do?
- Create Friends app to handle following/unfollowing between users
### Description of Task to be completed?
- Add Friend model class
- Add the CustomSerializer to verify the usernames
- Add the view classes
- Add the routes
### Functionality
- A user can follow and be followed by other users
- A user can view users he/she is following.(Available for other users)
- A user can view users following him/her.(Available for other users)
### How should this be manually tested
- clone the Repo 'git clone https://github.com/andela/ah-sealteam.git'
- Install Virtualenv `pip install virtualenv`
- Create the virtual environment `virtualenv venv`
- Activate the virtualenv `source venv/bin/activate`
- navigate to project folder `cd ah-sealteam`
- Install the dependencies `pip install -r requirements.txt`
- Run the migrations `python manage.py makemigrations && python manage.py migrate`
screen shot 2018-11-07 at 19 36 24

- Register a user via the endpoint `http://127.0.0.1:8000/api/users`. This also logins the user returning a token. (Register multiple users).
screen shot 2018-11-07 at 19 10 58`
- Follow one of the users using the endpoint POST `http://127.0.0.1:8000/api/profiles/USERNAME/follow`. The response returns the profile of the user followed
screen shot 2018-11-07 at 19 13 29
- Check the users following that user GET `http://127.0.0.1:8000/api/profiles/USERNAME/followers`
screen shot 2018-11-07 at 19 16 02
- Unfollow the user DELETE `http://127.0.0.1:8000/api/profiles/USERNAME/unfollow`
The response returns the profile of the unfollowed user
screen shot 2018-11-07 at 19 18 03
- Follow other users and check the users you're following GET `http://127.0.0.1:8000/api/profiles/USERNAME/following`
screen shot 2018-11-07 at 19 21 17

#### What are the relevant pivotal tracker stories?
[Finishes #161278918]

### CODE REVIEW

**Comment by rickynyairo** [comment]
@botnetdobbs why did you opt to create a new Friends application instead of using the existing profiles application?

**Review by rickynyairo — APPROVED** [review]
After further reading, I believe using a separate application to implement the feature was the right way to go.
Good work.

**Comment by botnetdobbs** [comment]
@rickynyairo Thanks...,

**Review by Adoniswalker — CHANGES_REQUESTED** [review]
Your PR seam to lower our test coverage, try to test all case scenarios

**Comment by botnetdobbs** [comment]
@Adoniswalker Thanks for the reminder. I've fixed that...,

**Review by Adoniswalker — APPROVED** [review]

**Review by susanwere — APPROVED** [review]

**Pull request merged**
