### PR TITLE
[Feature #161278925] Add article read time functionality

### PR DESCRIPTION
**Pull request by asheux**
#### What does this PR do?
- Creates the functionality to calculates the time the article takes the average human to read on the application.

#### Description of Task to be completed?
- The API takes the total word count of an article and translate it into minutes.  This is very crucial because it allows end users to prepare the time they need to read an article in full, also help them choose the right article for the right amount of available time they have.

#### How should this be manually tested?

```
$ git clone https://github.com/andela/ah-sealteam
$ cd ah-sealteam
$ python manage.py makemigrations
$ python manage.py migrate
$ python manage.py runserver
```
Then create an account on this url [127.0.0.1:8000](http://127.0.0.1:8000/#/) and post an article.
The output you get should display the read time of the article posted

#### Any background context you want to provide?

- The feature is implemented using PyPI module called ```readtime```. Visit the site for more information [PyPI](https://pypi.org/project/readtime/).

#### What are the relevant pivotal tracker stories?
[#161278925](https://www.pivotaltracker.com/n/projects/2205273/stories/161278925)

#### Screenshots (if appropriate) of the response you get

screenshot 2018-11-06 at 01 06 55

### CODE REVIEW

**Review by Adoniswalker — DISMISSED** [review]
deployment is unsuccessful. Kindly work on it

**Review by rickynyairo — APPROVED** [review]
Approved

**Review by botnetdobbs — APPROVED** [review]
Approved

**Review by gtsofa — COMMENTED** [review]
Read time feature works OK.

**Review by susanwere — APPROVED** [review]

**Pull request merged**
