### PR TITLE
chore Upgrade django #161278896

### PR DESCRIPTION
**Pull request by gtsofa**
## What does this Pull Request Do?
Upgrade django 1.11 to django 2.1

## Description of Task to be completed
Upgrading to django 2.1 because django 1.11 is no longer supported thus vulnerable to security, and
Django 2.x is the latest release of Django with full support of Python 3.x series.
## How should this be manually tested?
- On your local machine, clone the repository `https://github.com/andela/ah-sealteam` 
- Navigate to the folder `$ cd ah-sealteam`
- Run command `$ django --version` to see the version of django

### CODE REVIEW

**Comment by Adoniswalker** [comment]
Hi, My code is breaking. Kindly fix the bugs from upgrading

**Comment by gtsofa** [comment]
@Adoniswalker , what's breaking on your code...would you kindly highlight the bugs that you're getting?

**Review by rickynyairo — APPROVED** [review]
Approved

**Review by Adoniswalker — CHANGES_REQUESTED** [review]
Update the PR

**Review by Adoniswalker — APPROVED** [review]

**Review by susanwere — APPROVED** [review]

**Review by asheux — APPROVED** [review]

**Pull request merged**
